### ISSUE TITLE
uberon import missing axioms

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#158]
uberon_import.owl is missing axioms. for example the lumen-related axioms (see https://github.com/obophenotype/uberon/issues/1203)

is it intentional that axioms are missing? can we change that? how?

this would be required to test if we can state in HP/MP that the fact that a *thing* located in some *lumen* implies that said *thing* is part of the *wall that surrounds the lumen*.

Example of missing axioms for http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_0002297 :

- located_in some external acoustic meatus
- produced_by some apocrine sweat gland

ping @cmungall

**Comment by cmungall** [comment]
We only bring in a subset of ObjectProperties for the uberon import.

The more we bring in, the larger the module becomes, due to the syntactic locality module extraction algorithm (which essentially is the set of all reachable nodes).

Currently, bringing in located_in would have no effect since it is weaker than part-of, and the phenotype axioms don't explicitly mention it.

> this would be required to test if we can state in HP/MP that the fact that a thing located in some lumen implies that said thing is part of the wall that surrounds the lumen.

This wouldn't be a valid inference (and if it were, we would pre-materialize the part-of in uberon anyway).

The current import strategy prohibits experimentation, such as changing 'inheres in part of' to actually be 'inheres in located in' and testing the results. However, if we want to do this experiment we can just change the catalog to bring in all of uberon.

**Comment by drseb** [comment]
ok. we'll play around by bringing in uberon.owl. thanks
