### ISSUE TITLE
Discuss cl_import

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#233]
@cmungall we need to discuss cl_import with @sbello @nicolevasilevsky @mellybelly .

**Comment by cmungall** [comment]
Yes, more generally we should switch to an updated import pipeline using robot, and having a distinct terms.txt file for each source, 

https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/Makefile#L32-L35

For uberon/cl, I guess the issue is that we always get cl via the uberon ext release (which bundles cl). This has some advantages for other purposes, such as getting the bridging axioms to zfa and wbbt, but that doesn't really concern us for supporting ontology development. So simplifying here would be a good idea.

**Comment by drseb** [comment]
I just added cl_import , so I think this issue is solved for now
