### ISSUE TITLE
add CL terms to GO import

### ISSUE THREAD

**Issue by sbello** [obophenotype/upheno#273]
Please add the terms 
http://purl.obolibrary.org/obo/CL_0002256 term name: supporting cell of carotid body
http://purl.obolibrary.org/obo/CL_0002292 term name: type I cell of carotid body
to the GO import. Used in axioms for MP terms MP:0020840-MP:0020843

**Comment by drseb** [comment]
Do you mean cl or go import? sent from mobile-------- Originalnachricht --------Betreff: [obophenotype/upheno] add CL terms to GO import (#273)Von: Sue Bello An: obophenotype/upheno Cc: Subscribed Please add the terms
http://purl.obolibrary.org/obo/CL_0002256 term name: supporting cell of carotid body
http://purl.obolibrary.org/obo/CL_0002292 term name: type I cell of carotid body
to the GO import. Used in axioms for MP terms MP:0020840-MP:0020843

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/obophenotype/upheno","title":"obophenotype/upheno","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/obophenotype/upheno"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"add CL terms to GO import (#273)"}],"action":{"name":"View Issue","url":"https://github.com/obophenotype/upheno/issues/273"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/obophenotype/upheno/issues/273",
"url": "https://github.com/obophenotype/upheno/issues/273",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "add CL terms to GO import (#273)",
"sections": [
{
"text": "",
"activityTitle": "**Sue Bello**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sbello",
"facts": [
{
"name": "Repository: ",
"value": "obophenotype/upheno"
},
{
"name": "Issue #: ",
"value": 273
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"obophenotype/upheno\",\n\"issueId\": 273,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"obophenotype/upheno\",\n\"issueId\": 273\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/obophenotype/upheno/issues/273"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 352202342\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sbello** [comment]
The list of imports I see in protege do not include a separate CL import. As far as I could tell the CL terms are all under the GO import. If there is a separate CL import where would I find it to add it to the set I'm using with the MP?

**Comment by sbello** [comment]
Similar question for the CHEBI import, this also seems to be incorporated in the GO import when I look in protege, is this correct?

**Comment by drseb** [comment]
@sbello Don't look in protege. In mp-edit.owl (open in text editor) you see the following 
![screen shot 2018-07-03 at 10 07 03](https://user-images.githubusercontent.com/5172897/42206931-df5888d8-7ea8-11e8-9c1e-e1513fb2382d.png)

That means that cl and chebi are in their own imports-file. (there may be links between the import files, but I don't know why & where)


@cmungall @pnrobinson @balhoff  If anybody has an idea how we can makes import-requests easier to be collected at one central point, I would be happy to try it out. Now import-request-tickets are scattered among multiple repos. (And no, I don't want to create yet another repo). Can labels be shared across different repos?

**Comment by sbello** [comment]
@cmungall Is this on the agenda for the August workshop?

**Comment by cmungall** [comment]
@nicolevasilevsky can you make sure it's added

this will also be a topic of the obo tutorial too, we need better methods as a whole for doing this
