### ISSUE TITLE
Question: Should labels for ZP terms contain GO IRIs?

### ISSUE THREAD

**Issue by kshefchek** [obophenotype/upheno#495]
Currently ZP term labels contain the related GO IRI instead of the label, for example:

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/ZP_0104672">
        ...
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://purl.obolibrary.org/obo/GO_0000038 disrupted, abnormal</rdfs:label>
    </owl:Class>

Is this intended?

**Comment by matentzn** [comment]
These are not intended, but cant currently be avoided easily. I fixed a good number of them in the latest ZP release; like the one you shared here. Waiting for [this](https://github.com/OBOFoundry/purl.obolibrary.org/pull/545/files) to be merged. 

The reason they exist is because some ZP phenotypes refer to obsolete filler classes, for which no labels could be retrieved. However, for Monarch, this case (after above merge) should be neglidgible, as no record should be annoted against absoltete terms at ZFIN (they have QC against that).

**Comment by kshefchek** [comment]
Okay makes sense, I'll close
