### ISSUE TITLE
UPHENO:0001002 vs UPHENO:0001001

### ISSUE THREAD

**Issue by balhoff** [obophenotype/upheno#722]
In the Upheno release, there is a term 'phenotype' (UPHENO:0001001). But HP and MP phenotypes are not under this. There is another term, UPHENO:0001002, which is asserted to be the parent of HP and MP phenotypes. But UPHENO:0001002 has no other axioms at all. Was this a typo?

It doesn't seem like MP and HP are connected to Upheno phenotype at all.

**Comment by matentzn** [comment]
Thanks a lot @balhoff !

Ohh accident of the past.

- 'phenotype' (UPHENO:0001001) is the root of everything
- UPHENO:0001002 is not used in upheno 1, and not by anyone other than [OHMI](https://www.ebi.ac.uk/ols/search?q=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUPHENO_0001002&groupField=iri&exact=on&start=0). This being in uPheno 1 was a bug that is now fixed [in](https://github.com/obophenotype/upheno/pull/723). Thanks
- Since OHMI are using it (somewhat correctly) as "abnormal phenotype", I fixed the IRI in uPheno 2 to point to that one instead, so OHMI does not need to change anything. So thanks on behalf of them too :D (dont know them well :P)

**Comment by matentzn** [comment]
(you will get a long email later today, sorry)
