### ISSUE TITLE
abnormal relay of chemical signal pattern?

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#752]
In Dicty,  the cells when starving produce cAMP and secrete it and the next cell receives the signal through cAMP receptor and also produces cAMP and so on. 

Once a cell has ben stimulated it goes through a refractory period and cannot directly be stimulated again. Cells also produce a Phosphodiesterase that breaks down extra cAMP. All this is a tightly regulated relay mechanism and in about 6 sec interval one can see pulses of cAMP going through the cell population in dark field (also a transcription factor shuttles from nucleus to cytoplasm and back in synchrony to the pulses.

Therefore, as GO balks adding a term, I wonder if this is also something other systems also have.

AbnormalRelayOFCemicalSignal
AbnormallyDecreasedRelayOFCemicalSignal
AbnormallyIncreasedRelayOFCemicalSignal
AbnormallyAbsentRelayOFCemicalSignal

**Comment by pfey03** [comment]
We have over 250 strains annotated with either one of our terms:

DDPHENO:0001245 | aberrant cAMP signal relay
DDPHENO:0001246 | abolished cAMP signal relay
DDPHENO:0001397 | increased cAMP signal relay
DDPHENO:0001398 | decreased cAMP signal relay

also, one can also say oscillatory signaling or oscillatory signal relay and I could add a synonym to that effect. Oscillatory is also used here and there in dicty, but also see PMID: 20971631

**Comment by dosumis** [comment]
For discussion on phenotype call: We think that the oscillations themselves constitute a process that deserves its own term: 'extracellular cAMP oscillation' or 'extracellular cAMP wave' or maybe 'extracellular cAMP wave driving oscillation'.  By fat the preferred approach would be to use a process term to define the phenotype.  This would be much more comprehensible to users than something so compositional.

Have you already attempted to get a GO term and been rejected.  Could the GO process request be made more generic so that they can except it?  If not, can DictyBase consider making such terms themselves (that extend GO BP)?  (happy to discuss further)

**Comment by cmungall** [comment]
maybe the objection was about the wording of the definition?

**Comment by pfey03** [comment]
@cmungall maybe, but this could have been fixed. 

Possibly you can take this on and I can get a GO process? That would be awesome. and I've briefly read in a review that it is at least assumed that higher organisms have oscillatory signals.

**Comment by pfey03** [comment]
solved with GO
